"""
build_tools/builder.py
Builds protected, licensed launchers for customer executables.
"""

import sys
import json
import base64
import argparse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from loader.crypto_core import EnvVault, derive_license_secret, derive_encryption_secret
from loader.license_manager import LicenseManager
from loader.payload_encryptor import PayloadEncryptor


class BuildOrchestrator:
    def __init__(self):
        vault = EnvVault()
        self._master = vault.get_master_secret()
        # Only the DERIVED secrets get embedded into customer launchers.
        # The master secret never leaves this process.
        self._license_secret = derive_license_secret(self._master)
        self._encryption_secret = derive_encryption_secret(self._master)
        self._license_mgr = LicenseManager(self._license_secret)
        self._encryptor = PayloadEncryptor(self._encryption_secret)

    def protect_exe(self, exe_path, output_dir, customer_id, expiry_days=365,
                    hardware_bound=True, hardware_fingerprint=None) -> dict:
        if hardware_bound and not (hardware_fingerprint or '').strip():
            raise SystemExit(
                "[!] Refusing to build: hardware binding is enabled but no "
                "--hardware-id was supplied. The license would bind to this build\n"
                "    machine instead of the customer's PC.\n"
                "    Pass --hardware-id <customer HWID> or --no-hardware."
            )

        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        print(f"[+] Generating license for {customer_id}...")
        license_info = self._license_mgr.generate_license(
            customer_id=customer_id,
            expiry_days=expiry_days,
            features=['premium'],
            hardware_bound=hardware_bound,
            hardware_fingerprint=hardware_fingerprint,
        )
        if hardware_bound:
            print(f"[+] License bound to HWID: {hardware_fingerprint}")

        license_path = output_dir / 'license.key'
        with open(license_path, 'w') as f:
            f.write(license_info['license_key'])
        print("[+] License saved")

        print(f"[+] Encrypting {exe_path}...")
        payload_path = output_dir / 'payload.enc'
        meta = self._encryptor.encrypt_payload(Path(exe_path), payload_path)

        meta_path = output_dir / 'payload.meta'
        with open(meta_path, 'w') as f:
            json.dump(meta, f, indent=2)

        self._generate_loader(output_dir, license_info['license_key'])

        return {
            'customer_id': customer_id,
            'license_key': license_info['license_key'],
            'expires': license_info['expires'],
            'hardware_fingerprint': license_info['hardware_fingerprint'],
            'output_dir': str(output_dir),
        }

    def generate_license(self, customer_id, expiry_days=365,
                         hardware_id=None, no_hardware=False) -> dict:
        if not no_hardware and not (hardware_id or '').strip():
            raise SystemExit(
                "[!] Refusing to generate a hardware-bound license without "
                "--hardware-id (it would bind to this machine instead of the "
                "customer's PC). Pass --hardware-id <customer HWID> or --no-hardware."
            )
        return self._license_mgr.generate_license(
            customer_id=customer_id,
            expiry_days=expiry_days,
            features=['premium'],
            hardware_bound=not no_hardware,
            hardware_fingerprint=hardware_id,
        )

    def _generate_loader(self, output_dir: Path, license_key: str):
        embedded_license = repr(license_key)
        license_secret_b64 = repr(base64.b64encode(self._license_secret).decode())
        encryption_secret_b64 = repr(base64.b64encode(self._encryption_secret).decode())

        template = r'''#!/usr/bin/env python3
"""
Secure Launcher - Auto-generated by OrbitalLoader.
Do not edit manually.
"""

import os
import sys
import json
import time
import base64
import hashlib
import hmac
import zlib
import stat
import subprocess
import tempfile
import traceback
from datetime import datetime, timezone
from pathlib import Path

EMBEDDED_LICENSE = __EMBEDDED_LICENSE__
EMBEDDED_LICENSE_SECRET_B64 = __LICENSE_SECRET_B64__
EMBEDDED_ENCRYPT_SECRET_B64 = __ENCRYPT_SECRET_B64__


def _pad_b64(value):
    padding = 4 - (len(value) % 4)
    if padding != 4:
        value += '=' * padding
    return value


def _decode_embedded_secret(value):
    if not value:
        return None
    try:
        return base64.b64decode(_pad_b64(value.strip()))
    except Exception:
        return None


def _get_write_dirs():
    dirs = []
    try:
        if getattr(sys, 'frozen', False):
            dirs.append(Path(sys.executable).parent)
    except Exception:
        pass
    try:
        if '__file__' in dir():
            dirs.append(Path(__file__).parent)
    except Exception:
        pass
    try:
        dirs.append(Path.home() / 'Desktop')
    except Exception:
        pass
    return dirs


def _write_debug(content):
    text = str(content)
    for base in _get_write_dirs():
        try:
            base.mkdir(parents=True, exist_ok=True)
            with open(base / 'debug.txt', 'w', encoding='utf-8') as f:
                f.write(text)
            return
        except Exception:
            continue


def _save_hardware_id(hw_id):
    for base in _get_write_dirs():
        try:
            base.mkdir(parents=True, exist_ok=True)
            with open(base / 'hardware_id.txt', 'w', encoding='utf-8') as f:
                f.write(hw_id)
        except Exception:
            continue


def _get_hardware_fingerprint():
    # MUST stay in sync with loader/license_manager.py
    components = []
    if sys.platform == 'win32':
        try:
            import winreg
            with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, r'SOFTWARE\Microsoft\Cryptography') as key:
                components.append(str(winreg.QueryValueEx(key, 'MachineGuid')[0]))
        except Exception:
            pass
        try:
            import ctypes
            volume_serial = ctypes.c_ulong(0)
            if ctypes.windll.kernel32.GetVolumeInformationW(
                'C:' + os.sep, None, 0, ctypes.byref(volume_serial), None, None, None, 0
            ):
                components.append(str(volume_serial.value))
        except Exception:
            pass
    else:
        for path in ('/etc/machine-id', '/var/lib/dbus/machine-id'):
            try:
                with open(path, 'r') as f:
                    components.append(f.read().strip())
                break
            except Exception:
                continue
        if sys.platform == 'darwin':
            try:
                import subprocess
                result = subprocess.run(
                    ['ioreg', '-rd1', '-c', 'IOPlatformExpertDevice'],
                    capture_output=True, text=True, timeout=5,
                )
                for line in result.stdout.splitlines():
                    if 'IOPlatformUUID' in line:
                        components.append(line.split('"')[-2])
                        break
            except Exception:
                pass
    components.append(sys.platform)
    combined = '|'.join(str(c) for c in components if c)
    return hashlib.sha256(combined.encode()).hexdigest()[:32]


LICENSE_KEY = None
_license_sources = []
_search_paths = [
    Path.cwd(),
    Path(sys.executable).parent,
    Path.home() / 'Desktop',
    Path(__file__).parent if '__file__' in dir() else None,
    Path(sys._MEIPASS) if hasattr(sys, '_MEIPASS') else None,
]
for _base in _search_paths:
    if not _base:
        continue
    _test = _base / 'license.key'
    if _test.exists():
        try:
            with open(_test, 'r', encoding='utf-8') as f:
                _raw = f.read()
            _cleaned = _raw.encode('utf-8').decode('utf-8-sig')
            _cleaned = ''.join(c for c in _cleaned if not c.isspace())
            if _cleaned:
                LICENSE_KEY = _cleaned
                _license_sources.append('Found at: ' + str(_test) + ' (len=' + str(len(_cleaned)) + ')')
                break
            _license_sources.append('Empty file at: ' + str(_test))
        except Exception as e:
            _license_sources.append('Failed at ' + str(_test) + ': ' + str(e))

if not LICENSE_KEY and EMBEDDED_LICENSE:
    LICENSE_KEY = EMBEDDED_LICENSE
    _license_sources.append('Using embedded license')

if not LICENSE_KEY:
    _license_sources.append('No license found')


def validate_license(license_key, license_secret):
    debug_lines = []
    debug_lines.append('Key length: ' + str(len(license_key)))
    debug_lines.append('Key first 20: ' + license_key[:20])

    if not license_key:
        raise ValueError('No license provided')

    try:
        compressed = base64.urlsafe_b64decode(_pad_b64(license_key))
        bundle = json.loads(zlib.decompress(compressed))
    except Exception as e:
        raise ValueError('Invalid license format: ' + str(e))

    data = bundle.get('data', {})
    lic_hw = data.get('hardware_fingerprint', 'NONE')
    cur_hw = _get_hardware_fingerprint()

    debug_lines.append('Customer: ' + str(data.get('customer_id')))
    debug_lines.append('License HW: ' + str(lic_hw))
    debug_lines.append('Current HW: ' + cur_hw)
    debug_lines.append('Match: ' + str(lic_hw == cur_hw))
    debug_lines.append('HW bound: ' + str(data.get('hardware_bound')))
    try:
        debug_lines.append('Expires: ' + datetime.fromtimestamp(
            data.get('expires_at', 0), tz=timezone.utc).isoformat())
    except Exception:
        pass
    _write_debug('License validation:\n' + '\n'.join(debug_lines))

    payload = json.dumps(data, sort_keys=True).encode()
    expected_sig = hmac.new(license_secret, payload, hashlib.sha256).hexdigest()
    if not hmac.compare_digest(expected_sig, bundle.get('signature', '')):
        raise ValueError('Invalid license signature')

    if time.time() > data.get('expires_at', 0):
        raise ValueError('License expired')

    if data.get('hardware_bound'):
        if not lic_hw or lic_hw == 'NONE':
            raise ValueError('License is hardware-bound but contains no fingerprint')
        if lic_hw != cur_hw:
            raise ValueError('License bound to different hardware. Your hardware ID: ' + cur_hw)

    return data


def decrypt_payload(enc_path, meta, enc_secret):
    from cryptography.fernet import Fernet
    from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
    from cryptography.hazmat.primitives import hashes
    salt = base64.b64decode(meta['salt'])
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=480000,
    )
    key = base64.urlsafe_b64encode(kdf.derive(enc_secret))
    fernet = Fernet(key)
    with open(enc_path, 'rb') as f:
        encrypted = f.read()
    compressed = fernet.decrypt(encrypted)
    original = zlib.decompress(compressed)
    if hashlib.sha256(original).hexdigest() != meta['original_hash']:
        raise ValueError('Payload integrity check failed')
    return original


def _secure_write(path, data):
    with open(path, 'wb') as f:
        f.write(data)
    if sys.platform != 'win32':
        os.chmod(path, stat.S_IRWXU)


def execute_exe(data):
    fd, path = tempfile.mkstemp(suffix='.exe' if sys.platform == 'win32' else '')
    try:
        os.close(fd)
        _secure_write(path, data)
        result = subprocess.run([path] + sys.argv[1:])
        return result.returncode
    finally:
        try:
            os.unlink(path)
        except Exception:
            pass


def _show_error(title, message):
    if sys.platform == 'win32':
        try:
            import ctypes
            ctypes.windll.user32.MessageBoxW(0, message, title, 0x10)
        except Exception:
            pass
    else:
        print(title + ': ' + message, file=sys.stderr)


def _show_info(title, message):
    if sys.platform == 'win32':
        try:
            import ctypes
            ctypes.windll.user32.MessageBoxW(0, message, title, 0x40)
        except Exception:
            pass
    else:
        print(title + ': ' + message)


def main():
    _write_debug('License sources:\n' + '\n'.join(_license_sources))

    if not LICENSE_KEY:
        hw_id = _get_hardware_fingerprint()
        _save_hardware_id(hw_id)
        msg = (
            'No license found.\n\n'
            'Your hardware ID: ' + hw_id + '\n\n'
            'hardware_id.txt has been saved next to the launcher and on your Desktop.\n'
            'Send that file to receive a license key.'
        )
        _show_info('LICENSE REQUIRED', msg)
        return 1

    try:
        license_secret = _decode_embedded_secret(EMBEDDED_LICENSE_SECRET_B64)
        if license_secret is None:
            raise ValueError('Loader build error: license secret missing')
        license_data = validate_license(LICENSE_KEY, license_secret)
    except ValueError as e:
        err_str = str(e)
        if 'hardware ID:' in err_str:
            hw_id = err_str.split('hardware ID:')[-1].strip()
            _save_hardware_id(hw_id)
            err_str += (
                '\n\nhardware_id.txt has been saved next to the launcher and on your Desktop.\n'
                'Send that file to receive a new license key.'
            )
        _show_error('License Error', err_str)
        return 1
    except Exception:
        _write_debug('Unexpected error:\n' + traceback.format_exc())
        _show_error('Error', 'Unexpected error - see debug.txt')
        return 1

    try:
        enc_secret = _decode_embedded_secret(EMBEDDED_ENCRYPT_SECRET_B64)
        if enc_secret is None:
            raise ValueError('Loader build error: encryption secret missing')

        here = None
        if getattr(sys, 'frozen', False):
            here = Path(sys.executable).parent
        elif '__file__' in dir():
            here = Path(__file__).parent

        candidates = []
        if here:
            candidates.append(here)
        candidates.append(Path.cwd())
        if hasattr(sys, '_MEIPASS'):
            candidates.append(Path(sys._MEIPASS))

        enc_path = None
        meta_path = None
        for base in candidates:
            if (base / 'payload.enc').exists() and (base / 'payload.meta').exists():
                enc_path = base / 'payload.enc'
                meta_path = base / 'payload.meta'
                break

        if enc_path is None:
            raise ValueError('payload.enc / payload.meta not found next to the launcher')

        with open(meta_path, 'r', encoding='utf-8') as f:
            meta = json.load(f)

        payload = decrypt_payload(enc_path, meta, enc_secret)
        return execute_exe(payload)
    except ValueError as e:
        _show_error('Error', str(e))
        return 1
    except Exception:
        _write_debug('Execution error:\n' + traceback.format_exc())
        _show_error('Error', 'Unexpected error - see debug.txt')
        return 1


if __name__ == '__main__':
    sys.exit(main())
'''

        loader_source = (
            template
            .replace('__EMBEDDED_LICENSE__', embedded_license)
            .replace('__LICENSE_SECRET_B64__', license_secret_b64)
            .replace('__ENCRYPT_SECRET_B64__', encryption_secret_b64)
        )

        loader_path = output_dir / 'SecureLauncher.py'
        with open(loader_path, 'w', encoding='utf-8') as f:
            f.write(loader_source)
        print(f"[+] Launcher written to {loader_path}")


def build_parser():
    parser = argparse.ArgumentParser(
        prog='builder',
        description='OrbitalLoader build tool',
    )
    sub = parser.add_subparsers(dest='command', required=True)

    p_protect = sub.add_parser(
        'protect-exe',
        help='Encrypt an EXE, generate its license and build the launcher',
    )
    p_protect.add_argument('exe', type=str, help='Path to the EXE to protect')
    p_protect.add_argument('-o', '--output', type=str, default='./protected',
                           help='Output directory (default: ./protected)')
    p_protect.add_argument('--customer', type=str, required=True, help='Customer ID')
    p_protect.add_argument('--days', type=int, default=365,
                           help='License validity in days (default: 365)')
    p_protect.add_argument('--hardware-id', type=str, default=None,
                           help="Customer's hardware ID (contents of their hardware_id.txt)")
    p_protect.add_argument('--no-hardware', action='store_true',
                           help='Disable hardware binding')

    p_gen = sub.add_parser('generate-license',
                           help='Generate a standalone license key')
    p_gen.add_argument('--customer', type=str, required=True, help='Customer ID')
    p_gen.add_argument('--days', type=int, default=365,
                       help='License validity in days (default: 365)')
    p_gen.add_argument('--hardware-id', type=str, default=None,
                       help="Customer's hardware ID (contents of their hardware_id.txt)")
    p_gen.add_argument('--no-hardware', action='store_true',
                       help='Disable hardware binding')

    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()

    if args.command == 'protect-exe':
        if args.no_hardware and args.hardware_id:
            parser.error('--no-hardware and --hardware-id are mutually exclusive')
        orch = BuildOrchestrator()
        result = orch.protect_exe(
            exe_path=args.exe,
            output_dir=args.output,
            customer_id=args.customer,
            expiry_days=args.days,
            hardware_bound=not args.no_hardware,
            hardware_fingerprint=args.hardware_id,
        )
        print(json.dumps(result, indent=2))
        return 0

    if args.command == 'generate-license':
        if args.no_hardware and args.hardware_id:
            parser.error('--no-hardware and --hardware-id are mutually exclusive')
        orch = BuildOrchestrator()
        lic = orch.generate_license(
            customer_id=args.customer,
            expiry_days=args.days,
            hardware_id=args.hardware_id,
            no_hardware=args.no_hardware,
        )
        print('[+] License generated')
        print('Customer: ' + args.customer)
        print('Hardware ID: ' + (args.hardware_id or '(unbound)'))
        print('Expires: ' + lic['expires'])
        # Machine-readable line for the CI workflow.
        # URL-safe base64 never contains ':' so cut -d: -f2- is safe.
        print('LICENSE_KEY:' + lic['license_key'])
        return 0

    return 1


if __name__ == '__main__':
    sys.exit(main())
